# Template: evaluate an existing ITR under randomized data with evalITR.
# This is for evaluation, not rule learning. Replace vectors before running.

library(evalITR)

# T: observed randomized treatment, coded 0/1.
# That: cross-fitted or externally generated rule recommendation, coded 0/1.
# Y: observed outcome, where higher is better.
# ind: fold id if That was generated by cross-validation.

T <- df$treatment
Y <- df$outcome
That <- df$rule_recommendation
ind <- df$fold_id

# Population Average Prescriptive Effect.
pape <- PAPE(T = T, That = That, Y = Y)
print(pape)

# Cross-validated PAPE when the rule was learned inside folds.
pape_cv <- PAPEcv(T = T, That = as.matrix(That), Y = Y, ind = ind)
print(pape_cv)

# Budgeted evaluation: set budget to the maximum treated proportion.
pape_budget <- PAPE(T = T, That = That, Y = Y, budget = 0.30)
print(pape_budget)
