#!/usr/bin/env python3
"""Advisory subskill lookup for causal-consultant.

The helper maps a short interpreted signal string, plus optional project YAML,
to plausible subskills. It is intentionally advisory: the lead consultant and
core reviewers still decide whether any candidate should be used.
"""
from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any


SKILL_ROOT = Path(__file__).resolve().parents[1]
BOUNDARY_TOKEN = "zzboundaryzz"


@dataclass(frozen=True)
class CatalogItem:
    subskill_id: str
    catalog_role: str
    entrypoint: str | None
    use_for: str
    terms: tuple[str, ...]
    phase_boosts: dict[str, int]


CATALOG: tuple[CatalogItem, ...] = (
    CatalogItem(
        "01-domain-expert",
        "core_reviewer_emphasis",
        "subskills/01-domain-expert/SKILL.md",
        "domain meaning, construct validity, literature/common-practice context, mechanisms, and interpretation",
        (
            "domain",
            "scientific background",
            "construct validity",
            "mechanism",
            "effect scale",
            "external validity",
            "interpretation",
            "clinical meaning",
            "policy meaning",
            "literature",
            "common practice",
        ),
        {"project_exploration": 2, "causal_specification": 1, "report_production": 1},
    ),
    CatalogItem(
        "02-data-analyst",
        "core_reviewer_emphasis",
        "subskills/02-data-analyst/SKILL.md",
        "data reality, variable construction, timing, missingness, data quality, reproducibility, tables, and figures",
        (
            "data",
            "dataset",
            "schema",
            "variable",
            "codebook",
            "missingness",
            "selection",
            "row unit",
            "unit of observation",
            "timing",
            "support",
            "overlap",
            "file",
            "table",
            "figure",
            "plot",
            "reproducible",
        ),
        {"project_exploration": 2, "causal_specification": 1, "report_production": 2},
    ),
    CatalogItem(
        "03-method-lead",
        "core_reviewer_emphasis",
        "subskills/03-method-lead/SKILL.md",
        "causal claim, estimand, DAG/theory, assumptions, framework choice, diagnostics, and wording boundary",
        (
            "causal question",
            "estimand",
            "dag",
            "assumption",
            "identification",
            "confounding",
            "treatment",
            "exposure",
            "comparator",
            "outcome",
            "time zero",
            "follow up",
            "diagnostic",
            "sensitivity",
            "framework",
            "causal claim",
        ),
        {"causal_specification": 2, "report_production": 1},
    ),
    CatalogItem(
        "05-report-writer",
        "silent_report_writer",
        "subskills/05-report-writer/SKILL.md",
        "temporary working report, report synthesis, limitations, tables/figures text, and polished deliverables",
        (
            "report",
            "memo",
            "draft",
            "write up",
            "write-up",
            "deliverable",
            "methods section",
            "results section",
            "limitations",
            "caption",
            "appendix",
            "slides",
            "manuscript",
            "working report",
        ),
        {"report_production": 3, "causal_specification": 1},
    ),
    CatalogItem(
        "06-causal-discovery",
        "sidecar",
        "subskills/06-causal-discovery/SKILL.md",
        "exploratory graph learning, variable-screening ideas, constructed features, and discovery sidecar checks",
        (
            "causal discovery",
            "graph discovery",
            "structure learning",
            "pc algorithm",
            "fci",
            "ges",
            "lingam",
            "dag discovery",
            "edge",
            "orientation",
            "variable screening",
            "feature construction",
            "causal learn",
            "causal-learn",
            "tetrad",
        ),
        {"project_exploration": 1, "causal_specification": 1, "report_production": 1},
    ),
    CatalogItem(
        "07-randomized-assignment-and-experiments",
        "design_route",
        "subskills/07-randomized-assignment-and-experiments/SKILL.md",
        "randomized assignment, A/B tests, trials, encouragement designs, noncompliance, ITT/CACE framing, sample-ratio mismatch, CUPED, randomization inference, and experiment diagnostics",
        (
            "randomized",
            "randomised",
            "randomized controlled trial",
            "randomised controlled trial",
            "randomized trial",
            "randomised trial",
            "clinical trial",
            "field trial",
            "random assignment",
            "randomization",
            "randomisation",
            "experiment",
            "controlled experiment",
            "field experiment",
            "a b test",
            "ab test",
            "a/a test",
            "aa test",
            "split test",
            "treatment arm",
            "variant",
            "variants",
            "holdout",
            "assignment log",
            "allocation probability",
            "blocked randomization",
            "blocked randomisation",
            "stratified randomization",
            "stratified randomisation",
            "cluster randomized",
            "cluster randomised",
            "cluster randomized trial",
            "cluster randomised trial",
            "factorial experiment",
            "randomization inference",
            "randomisation inference",
            "permutation test",
            "intent to treat",
            "intention to treat",
            "itt",
            "cace",
            "complier average",
            "treatment receipt",
            "nonadherence",
            "sample ratio mismatch",
            "srm",
            "cuped",
            "variance reduction",
            "online controlled experiment",
            "online experiment",
            "noncompliance",
            "encouragement design",
        ),
        {"causal_specification": 2},
    ),
    CatalogItem(
        "08-single-time-observational-exposure",
        "design_route",
        "subskills/08-single-time-observational-exposure/SKILL.md",
        "single-time or baseline observational exposure, target-trial emulation, adjustment, propensity-style designs, matching, weighting, overlap, positivity, and ATE/ATT framing",
        (
            "observational",
            "cohort",
            "cohort study",
            "registry",
            "claims data",
            "claims",
            "ehr",
            "electronic health record",
            "electronic health records",
            "survey",
            "single time",
            "single-time",
            "point treatment",
            "baseline exposure",
            "baseline treatment",
            "observational exposure",
            "index date",
            "time zero",
            "target trial",
            "target trial emulation",
            "emulate a trial",
            "treated versus untreated",
            "treated vs untreated",
            "exposed versus unexposed",
            "exposed vs unexposed",
            "baseline confounders",
            "confounder adjustment",
            "adjustment set",
            "backdoor",
            "backdoor adjustment",
            "propensity score",
            "propensity score matching",
            "iptw",
            "ipw",
            "inverse probability weighting",
            "matching",
            "weighting",
            "overlap",
            "positivity",
            "support",
            "ate",
            "att",
        ),
        {"causal_specification": 2},
    ),
    CatalogItem(
        "09-longitudinal-gmethods",
        "design_route",
        "subskills/09-longitudinal-gmethods/SKILL.md",
        "time-varying treatment, treatment histories, time-varying confounding, sustained strategies, marginal structural models, g-formula, g-estimation, longitudinal TMLE, LMTP, and censoring-weighted g-methods",
        (
            "longitudinal",
            "longitudinal treatment",
            "longitudinal exposure",
            "time varying treatment",
            "time-varying treatment",
            "time varying exposure",
            "time-varying exposure",
            "time varying confounding",
            "time-varying confounding",
            "time varying confounder",
            "time-varying confounder",
            "confounders affected by prior treatment",
            "prior treatment",
            "repeated treatment",
            "repeated exposure",
            "treatment history",
            "treatment histories",
            "exposure history",
            "exposure histories",
            "person time",
            "person-time",
            "long format",
            "visit history",
            "follow up over time",
            "follow-up over time",
            "sustained treatment",
            "sustained exposure",
            "sustained strategy",
            "static regime",
            "dynamic regime",
            "dynamic regimes",
            "treatment regime",
            "treatment regimes",
            "sequential strategy",
            "sequential strategies",
            "marginal structural",
            "marginal structural model",
            "marginal structural models",
            "msm",
            "g method",
            "g methods",
            "g formula",
            "g-formula",
            "g computation",
            "g-computation",
            "parametric g formula",
            "parametric g-formula",
            "g estimation",
            "g-estimation",
            "structural nested",
            "structural nested model",
            "structural nested models",
            "sequential",
            "sequential exchangeability",
            "inverse probability of treatment",
            "inverse probability of censoring",
            "ipcw",
            "censoring weights",
            "treatment weights",
            "artificial censoring",
            "clone censor weight",
            "cloning censoring weighting",
            "cloning censoring weighting",
            "ltmle",
            "longitudinal tmle",
            "lmtp",
            "longitudinal modified treatment policy",
        ),
        {"causal_specification": 2},
    ),
    CatalogItem(
        "10-did-event-study",
        "design_route",
        "subskills/10-did-event-study/SKILL.md",
        "difference-in-differences, event studies, panel or repeated cross-section policy adoption, staggered timing, group-time ATT, synthetic DiD, DR-DiD, TWFE cautions, and parallel-trend checks",
        (
            "difference in differences",
            "difference-in-differences",
            "diff in diff",
            "diff-in-diff",
            "did",
            "dd",
            "event study",
            "event-study",
            "event time",
            "event-time",
            "dynamic effect",
            "dynamic effects",
            "panel",
            "repeated cross section",
            "repeated cross-section",
            "staggered",
            "staggered adoption",
            "staggered rollout",
            "adoption cohort",
            "treatment timing",
            "first treated",
            "not yet treated",
            "not-yet-treated",
            "never treated",
            "never-treated",
            "group time att",
            "group-time att",
            "cohort specific",
            "cohort-specific",
            "policy adoption",
            "pre post",
            "pre-post",
            "two way fixed effects",
            "two-way fixed effects",
            "twfe",
            "parallel trends",
            "parallel trend",
            "conditional parallel trends",
            "pretrend",
            "pre trend",
            "pre-trend",
            "pretrends",
            "pre trends",
            "pre-trends",
            "placebo trend",
            "anticipation",
            "forbidden comparison",
            "negative weights",
            "bacon decomposition",
            "goodman bacon",
            "callaway santanna",
            "callaway sant'anna",
            "sun abraham",
            "borusyak jaravel spiess",
            "did imputation",
            "did_imputation",
            "didimputation",
            "did2s",
            "did_multiplegt",
            "multiplegt",
            "fixest sunab",
            "sunab",
            "drdid",
            "dr did",
            "dr-did",
            "honestdid",
            "honest did",
            "synthetic did",
            "synthetic difference in differences",
            "synthdid",
            "csdid",
        ),
        {"causal_specification": 2},
    ),
    CatalogItem(
        "11-regression-discontinuity",
        "design_route",
        "subskills/11-regression-discontinuity/SKILL.md",
        "regression discontinuity, cutoffs, thresholds, running variables, sharp/fuzzy RD, regression kink, geographic/border RD, local randomization, bandwidths, manipulation/density checks, and RD report support",
        (
            "rd",
            "rdd",
            "regression discontinuity",
            "regression-discontinuity",
            "rd design",
            "rd analysis",
            "sharp regression discontinuity",
            "fuzzy regression discontinuity",
            "fuzzy rd",
            "sharp rd",
            "regression kink",
            "regression kink design",
            "rkd",
            "local randomization",
            "local randomisation",
            "cutoff",
            "threshold",
            "eligibility threshold",
            "score cutoff",
            "rank cutoff",
            "date cutoff",
            "time cutoff",
            "age cutoff",
            "boundary cutoff",
            "running variable",
            "forcing variable",
            "assignment variable",
            "bandwidth",
            "optimal bandwidth",
            "robust bias correction",
            "bias corrected",
            "rdrobust",
            "rdbwselect",
            "rdplot",
            "rddensity",
            "mccrary",
            "density test",
            "manipulation",
            "sorting",
            "bunching",
            "heaping",
            "donut rd",
            "placebo cutoff",
            "covariate continuity",
            "local polynomial",
            "multiple cutoffs",
            "multiple cutoff",
            "rdmulti",
            "rdlocrand",
            "rdpower",
            "geographic rd",
            "spatial rd",
            "border discontinuity",
            "boundary discontinuity",
            "discontinuity",
        ),
        {"causal_specification": 2},
    ),
    CatalogItem(
        "12-instrumental-variables",
        "design_route",
        "subskills/12-instrumental-variables/SKILL.md",
        "instrumental variables, encouragement, noncompliance, LATE/CACE, 2SLS, weak instruments, IV-DML, and Mendelian randomization checks",
        (
            "instrument",
            "instrumental",
            "instrumental variable",
            "instrumental variables",
            "iv",
            "iv analysis",
            "iv regression",
            "excluded instrument",
            "encouragement",
            "encouragement design",
            "lottery",
            "noncompliance",
            "non compliance",
            "non-compliance",
            "compliance",
            "exclusion restriction",
            "exclusion",
            "relevance",
            "monotonicity",
            "late",
            "cace",
            "complier",
            "compliers",
            "complier average",
            "local average treatment effect",
            "two stage",
            "two-stage",
            "two stage least squares",
            "two-stage least squares",
            "2sls",
            "liml",
            "fuller",
            "wald",
            "wald ratio",
            "reduced form",
            "first stage",
            "first-stage",
            "weak instrument",
            "weak instruments",
            "weak iv",
            "weak-instrument",
            "weak-instrument robust",
            "anderson rubin",
            "anderson-rubin",
            "conditional likelihood ratio",
            "clr",
            "overidentification",
            "overidentified",
            "sargan",
            "hansen j",
            "control function",
            "control-function",
            "dmliv",
            "orthogonal iv",
            "pliv",
            "iivm",
            "judge instrument",
            "judge leniency",
            "physician preference",
            "provider preference",
            "distance instrument",
            "preference instrument",
            "policy eligibility",
            "fuzzy rd",
            "fuzzy regression discontinuity",
            "mendelian randomization",
            "mendelian randomisation",
            "mr",
            "genetic instrument",
            "genetic instruments",
            "gwas",
            "snp",
            "snps",
            "polygenic score",
            "two sample mr",
            "two-sample mr",
            "ivw",
            "mr egger",
            "mr-egger",
            "pleiotropy",
            "horizontal pleiotropy",
            "mr-presso",
            "mr presso",
            "colocalization",
            "colocalisation",
        ),
        {"causal_specification": 2},
    ),
    CatalogItem(
        "13-synthetic-control-time-series",
        "design_route",
        "subskills/13-synthetic-control-time-series/SKILL.md",
        "synthetic control, augmented/generalized synthetic control, synthetic DiD, interrupted time series, Bayesian structural time series, aggregate interventions, donor pools, and time-series causal designs",
        (
            "synthetic control",
            "synthetic controls",
            "scm",
            "classic synthetic control",
            "augmented synthetic control",
            "augmented scm",
            "generalized synthetic control",
            "generalised synthetic control",
            "gsynth",
            "matrix completion",
            "panel counterfactual",
            "counterfactual panel",
            "synthetic did",
            "synthetic difference in differences",
            "synthetic difference-in-differences",
            "synthdid",
            "sdid",
            "interrupted time series",
            "interrupted time-series",
            "segmented regression",
            "comparative interrupted time series",
            "comparative interrupted time-series",
            "its",
            "bsts",
            "bayesian structural time series",
            "bayesian structural time-series",
            "causalimpact",
            "causal impact",
            "aggregate unit",
            "aggregate units",
            "one treated unit",
            "few treated units",
            "single treated unit",
            "treated unit",
            "treated units",
            "donor pool",
            "donor pools",
            "donor weights",
            "unit weights",
            "pre-period fit",
            "pre period fit",
            "pre-treatment fit",
            "pretreatment fit",
            "placebo test",
            "placebo tests",
            "permutation test",
            "permutation tests",
            "rmspe",
            "mspe",
            "leave one out",
            "leave-one-out",
            "intervention date",
            "policy shock",
            "comparative case study",
            "time series",
            "time-series",
            "state space",
            "state-space",
        ),
        {"causal_specification": 2},
    ),
    CatalogItem(
        "14-interference-spillovers",
        "design_route",
        "subskills/14-interference-spillovers/SKILL.md",
        "interference, spillovers, peer effects, contagion, contamination, SUTVA/no-interference violations, network/geographic exposure, partial interference, saturation designs, exposure mapping, and direct/indirect/total effects",
        (
            "interference",
            "spillover",
            "spillovers",
            "spill over",
            "spill-over",
            "spillovers",
            "sutva",
            "no interference",
            "no-interference",
            "violation of sutva",
            "network",
            "network exposure",
            "network interference",
            "peer effect",
            "peer effects",
            "social influence",
            "contagion",
            "diffusion",
            "contamination",
            "control contamination",
            "cluster exposure",
            "exposure mapping",
            "partial interference",
            "clustered interference",
            "interference within clusters",
            "treatment saturation",
            "saturation design",
            "randomized saturation",
            "randomised saturation",
            "two-stage randomization",
            "two stage randomization",
            "two-stage randomized",
            "two stage randomized",
            "graph cluster randomization",
            "graph cluster randomisation",
            "network experiment",
            "network experiment design",
            "treated neighbor",
            "treated neighbours",
            "treated neighbors",
            "neighbor exposure",
            "neighbour exposure",
            "treated-neighbor",
            "treated-neighbour",
            "degree",
            "homophily",
            "shared environment",
            "network missingness",
            "direct effect under interference",
            "indirect effect under interference",
            "overall effect",
            "total effect under interference",
            "spatial spillover",
            "geographic spillover",
            "distance exposure",
            "buffer zone",
            "market spillover",
            "equilibrium effect",
            "displacement effect",
            "contagion effect",
            "spillover did",
            "spillover iv",
            "spillover rd",
            "inferference",
            "interferenceci",
            "clusteredinterference",
            "latenetwork",
            "networkinference",
            "geocausal",
            "spatialeffect",
        ),
        {"causal_specification": 2},
    ),
    CatalogItem(
        "15-negative-controls-proximal",
        "design_route",
        "subskills/15-negative-controls-proximal/SKILL.md",
        "negative controls, placebo/falsification tests, empirical calibration, proximal causal inference, proxy variables, bridge functions, and unmeasured confounding probes",
        (
            "negative control",
            "negative controls",
            "negative control outcome",
            "negative control outcomes",
            "negative control exposure",
            "negative control exposures",
            "nco",
            "nce",
            "control outcome",
            "control exposure",
            "placebo outcome",
            "placebo exposure",
            "placebo test",
            "falsification",
            "falsification test",
            "falsification tests",
            "residual confounding",
            "hidden confounding",
            "unmeasured confounding",
            "unobserved confounding",
            "confounding bias",
            "bias diagnostic",
            "empirical calibration",
            "calibrated p value",
            "calibrated p-value",
            "calibrated confidence interval",
            "proximal",
            "proximal causal",
            "proximal causal inference",
            "proximal causal learning",
            "proximal g-computation",
            "proximal g computation",
            "proximal aipw",
            "proximal dml",
            "proxy",
            "proxies",
            "proxy variable",
            "proxy variables",
            "treatment proxy",
            "treatment proxies",
            "outcome proxy",
            "outcome proxies",
            "confounding proxy",
            "confounding proxies",
            "treatment confounding proxy",
            "outcome confounding proxy",
            "bridge function",
            "bridge functions",
            "confounding bridge",
            "outcome bridge",
            "treatment bridge",
            "proximal bridge",
            "pcl",
            "pci2s",
            "empiricalcalibration",
            "negative outcome",
            "negative exposure",
        ),
        {"causal_specification": 2},
    ),
    CatalogItem(
        "20-heterogeneous-effects",
        "target_goal",
        "subskills/20-heterogeneous-effects/SKILL.md",
        "heterogeneous treatment effects, subgroup or strata effects, CATE/ITE, GATE, effect modifiers, and exploratory heterogeneity",
        (
            "hte",
            "heterogeneous",
            "heterogeneity",
            "heterogeneous treatment effect",
            "heterogeneous treatment effects",
            "treatment heterogeneity",
            "subgroup",
            "subgroups",
            "strata",
            "stratum",
            "stratified",
            "stratification",
            "subpopulation",
            "subpopulations",
            "group-specific",
            "group specific",
            "gate",
            "cate",
            "ite",
            "conditional average treatment effect",
            "conditional treatment effect",
            "individual treatment effect",
            "effect modifier",
            "effect modifiers",
            "effect modification",
            "moderator",
            "moderation",
            "treatment effect heterogeneity",
            "causal tree",
            "causal trees",
            "causal forest",
            "causal forests",
            "grf",
            "s learner",
            "t learner",
            "x learner",
            "r learner",
            "dr learner",
            "meta learner",
            "meta learners",
            "metalearner",
            "metalearners",
            "best linear projection",
            "blp",
        ),
        {"causal_specification": 2},
    ),
    CatalogItem(
        "21-point-treatment-rules",
        "target_goal",
        "subskills/21-point-treatment-rules/SKILL.md",
        "single-point policy learning, individualized treatment rules, targeting, treatment prioritization, uplift, value, and decision constraints",
        (
            "point treatment rule",
            "single point rule",
            "single decision",
            "one-time decision",
            "one time decision",
            "baseline rule",
            "policy value",
            "policy learning",
            "policy rule",
            "policy tree",
            "policytree",
            "decision rule",
            "treatment rule",
            "treatment rules",
            "optimal treatment rule",
            "itr",
            "individualized",
            "individualised",
            "personalized",
            "personalised",
            "targeting",
            "treatment targeting",
            "treatment allocation",
            "allocation rule",
            "budgeted allocation",
            "empirical welfare",
            "welfare maximization",
            "prioritization",
            "prioritisation",
            "uplift",
            "qini",
            "auuc",
            "pape",
            "aupec",
            "value",
            "regret",
        ),
        {"causal_specification": 2},
    ),
    CatalogItem(
        "22-mediation",
        "target_goal",
        "subskills/22-mediation/SKILL.md",
        "mediation, direct and indirect effects, pathways, intermediate outcomes, and mechanism-oriented estimands",
        (
            "mediation",
            "mediated",
            "mediator",
            "mediators",
            "mediated effect",
            "mediated effects",
            "mechanism",
            "mechanisms",
            "indirect effect",
            "indirect effects",
            "direct effect",
            "direct effects",
            "pathway",
            "pathways",
            "intermediate outcome",
            "intermediate variable",
            "intermediate variables",
            "natural direct",
            "natural indirect",
            "nde",
            "nie",
            "controlled direct",
            "cde",
            "interventional direct",
            "interventional indirect",
            "path specific",
            "path-specific",
            "separable effect",
            "separable effects",
            "proportion mediated",
            "mediator outcome confounding",
            "mediator-outcome confounding",
            "exposure induced confounding",
            "exposure-induced confounding",
        ),
        {"causal_specification": 2},
    ),
    CatalogItem(
        "23-dose-response-effects",
        "target_goal",
        "subskills/23-dose-response-effects/SKILL.md",
        "dose-response and exposure-response targets for continuous, ordinal, multi-level, intensity, threshold, or modified exposure questions",
        (
            "dose response",
            "dose-response",
            "exposure response",
            "exposure-response",
            "dose response curve",
            "exposure response curve",
            "continuous treatment",
            "continuous exposure",
            "continuous dose",
            "multi-level treatment",
            "multilevel treatment",
            "treatment intensity",
            "exposure intensity",
            "threshold",
            "dose",
            "dosage",
            "dose level",
            "dose levels",
            "marginal dose",
            "generalized propensity score",
            "gps",
            "stochastic intervention",
            "stochastic shift",
            "shift intervention",
            "modified treatment policy",
            "modified treatment policies",
            "mtp",
            "lmtp",
            "tmle3shift",
        ),
        {"causal_specification": 2},
    ),
    CatalogItem(
        "24-transportability-generalizability",
        "target_goal",
        "subskills/24-transportability-generalizability/SKILL.md",
        "transportability, generalizability, target-population effects, trial-to-target translation, and site/population differences",
        (
            "transportability",
            "transportable",
            "transport",
            "transported",
            "generalizability",
            "generalisability",
            "generalise",
            "generalize",
            "external validity",
            "target population",
            "target-population",
            "target population effect",
            "trial to target",
            "trial-to-target",
            "trial generalizability",
            "trial transport",
            "population transport",
            "site transport",
            "site differences",
            "source target",
            "source-target",
            "sample to population",
            "selection diagram",
            "selection diagrams",
            "inverse odds sampling",
            "inverse odds of sampling",
            "sampling weights",
            "representativeness",
        ),
        {"causal_specification": 2},
    ),
    CatalogItem(
        "25-dynamic-treatment-policies",
        "target_goal",
        "subskills/25-dynamic-treatment-policies/SKILL.md",
        "dynamic treatment regimes, sequential treatment policies, adaptive strategies, and time-varying decision rules",
        (
            "dynamic treatment",
            "dynamic treatment regime",
            "dynamic treatment policy",
            "dynamic treatment policies",
            "sequential treatment",
            "sequential decision",
            "adaptive treatment",
            "adaptive strategy",
            "treatment strategy over time",
            "time-varying decision",
            "time varying decision",
            "decision over time",
            "regime",
            "treatment regime",
            "dynamic regime",
            "dynamic regimes",
            "q learning",
            "q-learning",
            "a learning",
            "a-learning",
            "outcome weighted learning",
            "residual weighted learning",
            "off policy evaluation",
            "off-policy evaluation",
            "fitted q",
            "fitted q evaluation",
            "sequential g formula",
            "sequential g-formula",
            "longitudinal modified treatment policy",
            "lmtp",
            "ltmle",
            "gformula",
            "g-formula",
            "smart trial",
            "SMART",
        ),
        {"causal_specification": 2},
    ),
    CatalogItem(
        "30-matching-weighting-balance",
        "implementation_support",
        "subskills/30-matching-weighting-balance/SKILL.md",
        "matching, weighting, propensity scores, balancing scores, overlap, positivity, trimming, entropy balancing, exact/coarsened matching, overlap weights, and balance diagnostics",
        (
            "matching",
            "matched",
            "nearest neighbor matching",
            "nearest-neighbor matching",
            "optimal matching",
            "full matching",
            "exact matching",
            "coarsened exact matching",
            "cem",
            "caliper",
            "calipers",
            "propensity",
            "propensity score",
            "propensity scores",
            "propensity score matching",
            "balancing score",
            "balancing scores",
            "weighting",
            "weights",
            "weighted",
            "ipw",
            "iptw",
            "inverse probability",
            "inverse probability weighting",
            "stabilized weight",
            "stabilized weights",
            "overlap weight",
            "overlap weights",
            "entropy balancing",
            "calibration weight",
            "calibration weights",
            "raking",
            "cbps",
            "overlap",
            "positivity",
            "common support",
            "trim",
            "trimming",
            "balance",
            "covariate balance",
            "standardized mean difference",
            "standardised mean difference",
            "smd",
            "love plot",
            "effective sample size",
            "ess",
        ),
        {"causal_specification": 2, "report_production": 1},
    ),
    CatalogItem(
        "31-doubly-robust-estimation",
        "implementation_support",
        "subskills/31-doubly-robust-estimation/SKILL.md",
        "AIPW, augmented IPW, TMLE, one-step estimators, efficient influence functions, nuisance models, targeted learning, and doubly robust estimation",
        (
            "doubly robust",
            "double robust",
            "aipw",
            "augmented ipw",
            "augmented inverse probability",
            "augmented inverse probability weighting",
            "tmle",
            "targeted maximum likelihood",
            "targeted learning",
            "targeted minimum loss",
            "one step",
            "one-step",
            "influence function",
            "efficient influence",
            "efficient influence function",
            "eif",
            "influence curve",
            "ic",
            "nuisance model",
            "nuisance models",
            "outcome nuisance",
            "propensity nuisance",
            "cross fitted aipw",
            "cross-fitted aipw",
            "drtmle",
            "tmle3",
            "ltmle",
            "super learner",
            "sl3",
        ),
        {"causal_specification": 2, "report_production": 1},
    ),
    CatalogItem(
        "32-double-machine-learning",
        "implementation_support",
        "subskills/32-double-machine-learning/SKILL.md",
        "orthogonal/double machine learning, double/debiased ML, cross-fitting, residualization, partially linear models, interactive regression models, orthogonal forests, and ML nuisance learners",
        (
            "double machine learning",
            "dml",
            "doubleml",
            "econml",
            "orthogonal",
            "orthogonal score",
            "orthogonal scores",
            "orthogonal machine learning",
            "neyman orthogonal",
            "neyman orthogonality",
            "debiased machine learning",
            "debiased ml",
            "double debiased",
            "double/debiased",
            "cross fitting",
            "cross-fitting",
            "cross fit",
            "cross-fit",
            "residualization",
            "residualisation",
            "partialling out",
            "partialling-out",
            "partially linear",
            "partially linear model",
            "plr",
            "irm",
            "interactive regression",
            "interactive regression model",
            "pliv",
            "iivm",
            "post lasso",
            "post-lasso",
            "double selection",
            "post double selection",
            "r learner",
            "r-learner",
            "dr learner",
            "dr-learner",
            "orthogonal forest",
            "orthogonal random forest",
            "causal forest dml",
            "causalforestdml",
            "nuisance learner",
            "nuisance learners",
            "random forest",
            "svm",
            "boosting",
            "xgboost",
            "lightgbm",
            "hdm",
        ),
        {"causal_specification": 2, "report_production": 1},
    ),
    CatalogItem(
        "33-survival-competing-risks",
        "implementation_support",
        "subskills/33-survival-competing-risks/SKILL.md",
        "time-to-event outcomes, censoring, competing risks, survival curves, fixed-time risk, RMST, hazards, incidence, survival CATE, causal survival forests, and survival prediction/nuisance support",
        (
            "survival",
            "time to event",
            "time-to-event",
            "time to event outcome",
            "time-to-event outcome",
            "duration",
            "censoring",
            "censored",
            "censoring weights",
            "inverse probability of censoring",
            "ipcw",
            "competing risk",
            "competing risks",
            "competing event",
            "competing events",
            "hazard",
            "hazards",
            "hazard ratio",
            "cox",
            "cox model",
            "cox proportional hazards",
            "proportional hazards",
            "aft",
            "accelerated failure time",
            "event time",
            "event-free survival",
            "mortality",
            "incidence",
            "rmst",
            "restricted mean survival",
            "restricted mean survival time",
            "cumulative incidence",
            "cumulative incidence function",
            "cif",
            "fine gray",
            "fine-gray",
            "subdistribution hazard",
            "cause-specific hazard",
            "cause specific hazard",
            "aalen johansen",
            "aalen-johansen",
            "left truncation",
            "delayed entry",
            "immortal time",
            "recurrent event",
            "recurrent events",
            "multi-state",
            "multistate",
            "kaplan meier",
            "kaplan-meier",
            "km curve",
            "weighted survival",
            "survival curve",
            "survival curves",
            "survival cate",
            "causal survival forest",
            "causal_survival_forest",
            "survival forest",
            "random survival forest",
            "brier score",
            "concordance",
            "c index",
            "time dependent auc",
            "time-dependent auc",
        ),
        {"causal_specification": 2, "report_production": 1},
    ),
)


MODULE_TYPE_BY_CATALOG_ROLE = {
    "design_route": "design_route",
    "target_goal": "target_goal",
    "implementation_support": "implementation_support",
    "sidecar": "discovery_sidecar",
    "silent_report_writer": "report_support",
}

DEFAULT_RECOMMENDATION_ROLES = {
    "design_route",
    "target_goal",
    "implementation_support",
    "sidecar",
}


NEGATION_TERMS = {
    "not",
    "no",
    "without",
    "never",
    "lack",
    "lacks",
    "lacking",
    "non",
    "neither",
    "nor",
    "cannot",
    "cant",
    "isnt",
    "arent",
    "wasnt",
    "werent",
    "doesnt",
    "dont",
    "didnt",
}


def normalize(text: str) -> str:
    text = text.lower()
    text = re.sub(r"['`]", "", text)
    text = re.sub(r"[^a-z0-9]+", " ", text)
    return re.sub(r"\s+", " ", text).strip()


def normalize_with_boundaries(text: str) -> str:
    text = text.lower()
    text = re.sub(r"['`]", "", text)
    text = re.sub(r"[\n\r.,;:!?()\[\]{}]+", f" {BOUNDARY_TOKEN} ", text)
    text = re.sub(r"[^a-z0-9]+", " ", text)
    return re.sub(r"\s+", " ", text).strip()


def strip_artifact_index(text: str) -> str:
    """Remove the fixed artifact registry so it does not create false matches."""
    kept: list[str] = []
    skip_indent: int | None = None
    for line in text.splitlines():
        stripped = line.strip()
        indent = len(line) - len(line.lstrip(" "))
        if re.match(r"^\s*artifact_index\s*:", line):
            skip_indent = indent
            continue
        if skip_indent is not None:
            if stripped and indent <= skip_indent and not stripped.startswith("- "):
                skip_indent = None
            else:
                continue
        kept.append(line)
    return "\n".join(kept)


def extract_project_signal_text(text: str) -> str:
    """Return rough YAML value text without requiring PyYAML."""
    text = strip_artifact_index(text)
    values: list[str] = []
    ignored = {
        "null",
        "[]",
        "{}",
        "true",
        "false",
        "unknown",
        "not_started",
        "not_ready",
        "not_reviewed",
        "project_exploration",
        "question",
        "exploratory",
    }
    ignored_normalized = {normalize(value) for value in ignored}
    for raw_line in text.splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line or line == "---":
            continue
        if line.startswith("- "):
            value = line[2:].strip()
        elif ":" in line:
            value = line.split(":", 1)[1].strip()
        else:
            continue
        value = value.strip().strip("\"'")
        if not value or normalize(value) in ignored_normalized:
            continue
        values.append(value)
    return " ".join(values)


def extract_current_phase(text: str) -> str | None:
    match = re.search(r"(?m)^\s*current_phase\s*:\s*[\"']?([^\"'\n#]+)", text)
    if not match:
        return None
    return normalize(match.group(1)).replace(" ", "_")


def read_project(path: str | None) -> tuple[str, str | None]:
    if not path:
        return "", None
    project_path = Path(path)
    if not project_path.exists():
        raise SystemExit(f"Project file not found: {project_path}")
    raw = project_path.read_text(encoding="utf-8")
    return extract_project_signal_text(raw), extract_current_phase(raw)


def word_positions(text: str) -> list[str]:
    return text.split()


def is_negated_context(words: list[str], start_word: int) -> bool:
    context = words[max(0, start_word - 6) : start_word]
    if BOUNDARY_TOKEN in context:
        context = context[context.index(BOUNDARY_TOKEN) + 1 :]
    for idx, word in enumerate(context):
        if word == "not" and idx + 1 < len(context) and context[idx + 1] == "yet":
            continue
        if word in NEGATION_TERMS:
            return True
    return False


def term_hits(norm_text: str, term: str) -> list[dict[str, Any]]:
    norm_term = normalize(term)
    if not norm_term:
        return []
    pattern = re.compile(rf"(?<![a-z0-9]){re.escape(norm_term)}(?![a-z0-9])")
    words_before_cache = word_positions(norm_text)
    hits: list[dict[str, Any]] = []
    for match in pattern.finditer(norm_text):
        start_word = len(norm_text[: match.start()].split())
        hits.append(
            {
                "term": term,
                "negated": is_negated_context(words_before_cache, start_word),
            }
        )
    return hits


def score_term(term: str) -> int:
    return 3 if len(normalize(term).split()) > 1 else 1


def available(entrypoint: str | None) -> bool:
    if not entrypoint:
        return False
    return (SKILL_ROOT / entrypoint).exists()


def recommendation_for(item: CatalogItem, norm_text: str, phase: str | None) -> dict[str, Any] | None:
    positive: list[str] = []
    negated: list[str] = []
    raw_score = 0
    for term in item.terms:
        for hit in term_hits(norm_text, term):
            if hit["negated"]:
                negated.append(term)
            else:
                positive.append(term)
                raw_score += score_term(term)

    if raw_score == 0:
        return None

    phase_boost = item.phase_boosts.get(phase or "", 0)
    score = raw_score + phase_boost
    exists = available(item.entrypoint)
    notes: list[str] = []
    if phase_boost:
        notes.append(f"phase boost: {phase}")
    if negated:
        notes.append("some related terms appeared in negated or contrastive context; review manually")
    if not exists:
        notes.append("candidate only; this subskill is not bundled yet")

    return {
        "subskill_id": item.subskill_id,
        "catalog_role": item.catalog_role,
        "module_type": MODULE_TYPE_BY_CATALOG_ROLE.get(item.catalog_role),
        "available": exists,
        "entrypoint": item.entrypoint if exists else None,
        "candidate_entrypoint": item.entrypoint,
        "score": score,
        "matched_terms": sorted(set(positive), key=positive.index),
        "negated_or_contrast_terms": sorted(set(negated), key=negated.index),
        "use_for": item.use_for,
        "notes": notes,
    }


def build_recommendations(
    signals: str,
    project_text: str,
    project_phase: str | None,
    phase_override: str | None,
    top_n: int,
    available_only: bool,
    include_team_modules: bool,
) -> dict[str, Any]:
    phase = phase_override or project_phase
    combined = normalize_with_boundaries(f"{project_text}\n{signals}")
    results = []
    for item in CATALOG:
        if not include_team_modules and item.catalog_role not in DEFAULT_RECOMMENDATION_ROLES:
            continue
        result = recommendation_for(item, combined, phase)
        if not result:
            continue
        if available_only and not result["available"]:
            continue
        results.append(result)

    results.sort(key=lambda row: (-row["score"], row["subskill_id"]))
    return {
        "advisory_only": True,
        "phase": phase,
        "recommendations": results[:top_n],
        "reminder": (
            "Use this as specialist recall for method_lead triage only. Raw candidates are not activations or "
            "user-facing recommendations; method_lead decides fit after reading domain_expert, "
            "data_analyst, and project state."
        ),
    }


def list_catalog(available_only: bool) -> dict[str, Any]:
    items = []
    for item in CATALOG:
        exists = available(item.entrypoint)
        if available_only and not exists:
            continue
        items.append(
            {
                "subskill_id": item.subskill_id,
                "catalog_role": item.catalog_role,
                "module_type": MODULE_TYPE_BY_CATALOG_ROLE.get(item.catalog_role),
                "available": exists,
                "entrypoint": item.entrypoint if exists else None,
                "candidate_entrypoint": item.entrypoint,
                "use_for": item.use_for,
            }
        )
    return {"catalog": items}


def main() -> None:
    parser = argparse.ArgumentParser(description="Advisory subskill lookup for causal-consultant.")
    parser.add_argument("--signals", default="", help="Short interpreted signal string from the lead consultant.")
    parser.add_argument("--project", default=None, help="Optional project YAML path.")
    parser.add_argument("--phase", default=None, help="Optional current phase override.")
    parser.add_argument("--top-n", type=int, default=5, help="Maximum number of recommendations.")
    parser.add_argument("--available-only", action="store_true", help="Return only currently bundled subskills.")
    parser.add_argument(
        "--include-team-modules",
        action="store_true",
        help="Include core reviewers and report writer in scored recommendations. By default, scored recommendations focus on specialist method/task/sidecar modules because the core team already runs through workflow.",
    )
    parser.add_argument("--list-catalog", action="store_true", help="List the catalog without scoring.")
    args = parser.parse_args()

    if args.list_catalog:
        print(json.dumps(list_catalog(args.available_only), indent=2))
        return

    project_text, project_phase = read_project(args.project)
    if not args.signals and not project_text:
        raise SystemExit("Provide --signals, --project, or --list-catalog.")

    payload = build_recommendations(
        signals=args.signals,
        project_text=project_text,
        project_phase=project_phase,
        phase_override=args.phase,
        top_n=args.top_n,
        available_only=args.available_only,
        include_team_modules=args.include_team_modules,
    )
    print(json.dumps(payload, indent=2))


if __name__ == "__main__":
    main()
